BEGIN TRANSACTION;
DROP TABLE IF EXISTS devices;
CREATE TABLE devices(mac_address TEXT, product_id INTEGER, name TEXT, serial_number TEXT, battery TEXT, device_rssi TEXT, hub_rssi TEXT, version BLOB, custommode INTEGER);
DROP TABLE IF EXISTS hubs;
CREATE TABLE hubs(mac_address TEXT, led_mode INTEGER, pairing_mode INTEGER, state INTEGER, uptime INTEGER );
DROP TABLE IF EXISTS doors;
CREATE TABLE doors(mac_address TEXT, lockingmode INTEGER, curfewenabled INTEGER, curfews TEXT);
DROP TABLE IF EXISTS feeders;
CREATE TABLE feeders(mac_address TEXT, bowltype INTEGER, bowl1 INTEGER, bowl2 INTEGER, bowltarget1 INTEGER, bowltarget2 INTEGER, close_delay INTEGER );
DROP TABLE IF EXISTS tagmap;
CREATE TABLE tagmap(mac_address TEXT, deviceindex INTEGER, tag TEXT, profile TEXT, UNIQUE (mac_address, deviceindex) ON CONFLICT REPLACE );
DROP TABLE IF EXISTS pets;
CREATE TABLE pets(tag TEXT, name TEXT, species INTEGER );
DROP TABLE IF EXISTS petstate;
CREATE TABLE petstate(tag TEXT, mac_address TEXT, timestamp TEXT, state BLOB );
DROP TABLE IF EXISTS devicestate;
CREATE TABLE devicestate(mac_address TEXT, offset INTEGER, length INTEGER, data TEXT, UNIQUE (mac_address, offset, length) ON CONFLICT REPLACE );
DROP TABLE IF EXISTS devicecounter;
CREATE TABLE devicecounter(mac_address TEXT, send INTEGER, retrieve INTEGER );
COMMIT;
